spring.application.name=Logistics
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/school_backend_manage
spring.datasource.username=root
spring.datasource.password=root
server.port=8080
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
logging.level.com.dahuang.logistics=DEBUG
#langchain4j.open-ai.chat-model.base-url=https://api.deepseek.com
#langchain4j.open-ai.chat-model.api-key=sk-6e6451de107a48acbb1048172fb89f69
#langchain4j.open-ai.chat-model.model-name=deepseek-chat

